# -*- coding: utf-8 -*-
"""IA Rule34

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvkSNT6KZPQmA3mPyCtkp2Ezb8WGWNYD
"""

import random

text = ""

Respuesta = ["https://rule34.xxx/index.php?page=post&s=view&id=7678615" , "https://rule34.xxx/index.php?page=post&s=view&id=7678736" , "https://rule34.xxx/index.php?page=post&s=view&id=7678732" , "https://rule34.xxx/index.php?page=post&s=view&id=7678385" , "https://rule34.xxx/index.php?page=post&s=view&id=7678079" , "https://rule34.xxx/index.php?page=post&s=view&id=7677822" , "https://rule34.xxx/index.php?page=post&s=view&id=7678175" , "https://rule34.xxx/index.php?page=post&s=view&id=7669660" , "https://rule34.xxx/index.php?page=post&s=view&id=7665105" , "https://rule34.xxx/index.php?page=post&s=view&id=7664364" , "https://rule34.xxx/index.php?page=post&s=view&id=7648837" , "https://rule34.xxx/index.php?page=post&s=view&id=7639295" , "https://rule34.xxx/index.php?page=post&s=view&id=7665294" , "https://rule34.xxx/index.php?page=post&s=view&id=5476328" , "https://rule34.xxx/index.php?page=post&s=view&id=5229213" , "https://rule34.xxx/index.php?page=post&s=view&id=5124322" , "https://rule34.xxx/index.php?page=post&s=view&id=6087874" , "https://rule34.xxx/index.php?page=post&s=view&id=5163263" , "https://rule34.xxx/index.php?page=post&s=view&id=4662605" , "https://www.hiqqu.com/view=ed02" , "https://futapo.com/wp-content/uploads/2021/12/Dynamo-x-Futa-Aria-Chaoz.gif" , "https://img2.rule34.us/images/c7/04/c704928f11651ef4a307303d8b198c7e.gif" , "https://us.rule34.xxx//images/5558/c737f63bd8182b84b4a87d0b1fbad3e9.gif?6325172" , "https://us.rule34.xxx//images/6776/47267b208949c72d942a374f2bc6f8db.jpeg?7735778" , "https://rule34.xxx/index.php?page=post&s=view&id=7708862" , "https://rule34.xxx/index.php?page=post&s=view&id=7625194" , "https://rule34.xxx/index.php?page=post&s=view&id=6665013"]
Respuesta = random.choice(Respuesta)
print("Bienvenido a IA rule 34")
print("Presiona enter para darte un link aleatorio de rule34")
print("NOTA: el programa puede repetir los links, pero eso no quiere decir que sean todos los links que hay")
print("No me hago responable de la salud mental de el usuario al salir de aqui (creeme hay cosas ricas y raras)")
input()
print("El programa esta decidiendo...presiona enter para continuar")
input()
print(Respuesta +  " Seleccionado en 0.2 segundos")